import React from 'react';

const Dotplot = () => (
  <article>
    <p>
After the data has been processed, the user will be prompted to download a
dotplot-results.zip file that contains the results in three subfolders. By
default the unzipped parent folder will be named &quot;results&quot; but this name can
be modified as desired. The subfolders are:
    </p>
    <p>
1) SVGs: This folder contains the dot plot and heat map images, as well
as a legend. The output bait vs bait and prey vs prey images are the
clustered distance matrices visualized as heat maps. In contrast to
similar images generated by our correlation yool, baits (or preys) in
these images have not been subjected to correlation analysis prior to
clustering. Instead, the metric used is the distance metric calculated
from the clustering option specified above. These files can be opened
and edited in Adobe Illustrator or a similar program.
2) PDFs: This contains the same images as in the SVG folder but in
PDF format.
3) InteractiveFiles: Contains plain text files formatted for our
interactive viewer found at ProHits-viz that allows navigation and
analysis of images. These files should be loaded directly into that
tool without modification. Their extension is &quot;-interactive.txt&quot;.
4) CytoscapeFiles: This folder contains plain text files for importing
to Cytoscape. The file &quot;bait-prey-cytoscape.txt&quot; contains only
bait-prey pairs that have passed the primary filter, with the abundance
equal to its post-transformation value (after control subtraction, normalization,
etc.). This allows users to import only desired bait-prey pairs into
Cytoscape with an abundance value suitable for edge-weighting that has
beed processed according to the user&apos;s need. Two additional files are
also present in this folder that contain all bait-bait and prey-prey
pairs from the distance matrices with an additional column containing
the distance metric itself that can be used for filtering which pairs
will be displayed in Cytoscape. These files are generated so that users
can view bait-bait and prey-prey information in a network format as
an alternative the heat map format we provide here.
5) OtherFiles: This folder contains bait-bait and prey-prey dendrograms
and will contain additional files generated by the nested clustering
option, if selected. Finally, the &quot;results&quot; folder will also contain
a log file the contains information on the input parameters that were
selected for the user&apos;s future reference (e.g. to assist with writing
the Methods section for a manuscript).
    </p>
  </article>
);

export default Dotplot;
